name: Deploy Demo to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
      
    - name: "Install Dependencies"
      run: npm ci
      working-directory: demo
      
    - name: "Build static Website"
      run: npm run generate
      working-directory: demo
      
    - name: "add .nojekyll"
      run: touch .nojekyll
      working-directory: demo/dist/
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.5
      with:
        BRANCH: demo
        FOLDER: demo/dist/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        SINGLE_COMMIT: true
        CLEAN: true
